# Generated by Django 2.0.7 on 2019-09-01 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.FloatField(blank=True)),
                ('cholesterol', models.FloatField(blank=True)),
                ('uric_acid', models.FloatField(blank=True)),
                ('created_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='urine_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leukocytes', models.FloatField(blank=True)),
                ('nitrate', models.FloatField(blank=True)),
                ('urobilinogen', models.FloatField(blank=True)),
                ('protein', models.FloatField(blank=True)),
                ('ph', models.FloatField(blank=True)),
                ('blood', models.FloatField(blank=True)),
                ('sp_gravity', models.FloatField(blank=True)),
                ('ketone', models.FloatField(blank=True)),
                ('bilirubin', models.FloatField(blank=True)),
                ('glucose', models.FloatField(blank=True)),
                ('ascorbic_acid', models.FloatField(blank=True)),
                ('created_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='Vital_sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('temperature', models.FloatField(blank=True)),
                ('pulse', models.FloatField(blank=True)),
                ('bp_systolic', models.FloatField(blank=True)),
                ('bp_diastolic', models.FloatField(blank=True)),
                ('sto2', models.FloatField(blank=True)),
                ('created_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
