# Generated by Django 2.0.7 on 2019-09-02 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190901_1006'),
        ('sunya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blood_test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blood_test',
            name='user',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vital_sign',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vital_sign',
            name='user',
        ),
        migrations.AddField(
            model_name='health',
            name='blood_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunya.Blood_test'),
        ),
        migrations.AddField(
            model_name='health',
            name='urine_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunya.Urine_test'),
        ),
        migrations.AddField(
            model_name='health',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AddField(
            model_name='health',
            name='vital_sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunya.Vital_sign'),
        ),
    ]
