# Generated by Django 2.0.7 on 2019-09-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0002_auto_20190908_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='blood_strip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='urine_strip',
            field=models.IntegerField(default=0),
        ),
    ]
