# Generated by Django 2.0.7 on 2019-09-02 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0003_auto_20190902_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_test',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blood_test',
            name='glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blood_test',
            name='uric_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='blood_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunya.Blood_test'),
        ),
        migrations.AlterField(
            model_name='health',
            name='urine_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunya.Urine_test'),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='ascorbic_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='bilirubin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='blood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='ketone',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='leukocytes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='nitrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='sp_gravity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urine_test',
            name='urobilinogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='bp_diastolic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='bp_systolic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='pulse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='sto2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vital_sign',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
