# Generated by Django 2.0.7 on 2019-09-02 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0004_auto_20190902_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='blood_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunya.Blood_test'),
        ),
        migrations.AlterField(
            model_name='health',
            name='urine_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunya.Urine_test'),
        ),
        migrations.AlterField(
            model_name='health',
            name='vital_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunya.Vital_sign'),
        ),
    ]
