# Generated by Django 2.0.7 on 2019-09-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0005_auto_20190902_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='blood_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunya.Blood_test'),
        ),
        migrations.AlterField(
            model_name='health',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='health',
            name='urine_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunya.Urine_test'),
        ),
    ]
