# Generated by Django 2.0.7 on 2019-09-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0008_auto_20190902_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='blood_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunya.Blood_test'),
        ),
        migrations.AlterField(
            model_name='health',
            name='urine_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sunya.Urine_test'),
        ),
    ]
