# Generated by Django 2.0.7 on 2019-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0010_auto_20190925_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='blood_sensor',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='bp_sensor',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='ecg',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='glucose_device',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='measuring_tool',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='pulse_sensor',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='temperature_sensor',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='urine_device',
            field=models.CharField(default='f', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='weighing_machine',
            field=models.CharField(default='f', max_length=2),
        ),
    ]
