# Generated by Django 2.0.7 on 2019-09-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0011_auto_20190925_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='dob',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
