# Generated by Django 2.0.7 on 2019-10-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunya', '0012_clients_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='imei',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
