# Generated by Django 2.0.7 on 2019-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_orguser',
            field=models.BooleanField(default=False),
        ),
    ]
